//UI -> Worker messages
const MSGID_SOUND_REQUEST_RESULT = "SOUND_REQUEST_RESULT";

//Worker -> UI messages
const MSGID_LOAD_SOUND_REQUEST = "LOAD_SOUND_REQUEST";
const MSGID_UNLOAD_SOUND_REQUEST = "UNLOAD_SOUND_REQUEST";
const MSGID_PLAY_SOUND_REQUEST = "PLAY_SOUND_REQUEST";
const MSGID_PAUSE_SOUND_REQUEST = "PAUSE_SOUND_REQUEST";
const MSGID_STOP_SOUND_REQUEST = "STOP_SOUND_REQUEST";
const MSGID_GET_SOUND_LEN_REQUEST = "GET_SOUND_LEN_REQUEST";
const MSGID_GET_SOUND_POS_REQUEST = "GET_SOUND_POS_REQUEST";
const MSGID_SET_SOUND_POS_REQUEST = "SET_SOUND_POS_REQUEST";
const MSGID_LOOP_SOUND_REQUEST = "LOOP_SOUND_REQUEST";