//UI -> Worker messages
const MSGID_SOUND_REQUEST_RESULT = 6;

//Worker -> UI messages
const MSGID_LOAD_SOUND_REQUEST = 50;
const MSGID_UNLOAD_SOUND_REQUEST = 51;
const MSGID_PLAY_SOUND_REQUEST = 52;
const MSGID_PAUSE_SOUND_REQUEST = 53;
const MSGID_STOP_SOUND_REQUEST = 54;
const MSGID_GET_SOUND_LEN_REQUEST = 55;
const MSGID_GET_SOUND_POS_REQUEST = 56;
const MSGID_SET_SOUND_POS_REQUEST = 57;
const MSGID_LOOP_SOUND_REQUEST = 58;