//UI -> Worker messages
const MSGID_INPUT_RESULT = "INPUT_RESULT";

//Worker -> UI messages
const MSGID_SHOW_CONSOLE = "SHOW_CONSOLE";
const MSGID_HIDE_CONSOLE = "HIDE_CONSOLE";
const MSGID_PRINT = "PRINT";
const MSGID_INPUT_REQUEST = "INPUT_REQUEST";
const MSGID_CLEAR_CONSOLE = "CLEAR_CONSOLE";