//UI -> Worker messages
const MSGID_SPRITE_SHEET_REF_REQUEST_RESULT = 7;
const MSGID_SPRITE_SHEET_REQUEST_RESULT = 8;

//Worker -> UI messages
const MSGID_SPRITE_SHEET_REF_REQUEST = 70;
const MSGID_LOAD_SPRITE_SHEET_REQUEST = 71;
const MSGID_UNLOAD_SPRITE_SHEET_REQUEST = 72;
const MSGID_DRAW_SPRITE_SHEET_FRAMES_REQUEST = 73;
const MSGID_GET_SPRITE_SHEET_FRAME_WIDTH_REQUEST = 74;
const MSGID_GET_SPRITE_SHEET_FRAME_HEIGHT_REQUEST = 75;