//UI -> Worker messages
export const MSGID_SPRITE_SHEET_REF_REQUEST_RESULT = "SPRITE_SHEET_REF_REQUEST_RESULT";
export const MSGID_SPRITE_SHEET_REQUEST_RESULT = "SPRITE_SHEET_REQUEST_RESULT";

//Worker -> UI messages
export const MSGID_SPRITE_SHEET_REF_REQUEST = "SPRITE_SHEET_REF_REQUEST";
export const MSGID_LOAD_SPRITE_SHEET_REQUEST = "LOAD_SPRITE_SHEET_REQUEST";
export const MSGID_UNLOAD_SPRITE_SHEET_REQUEST = "UNLOAD_SPRITE_SHEET_REQUEST";
export const MSGID_DRAW_SPRITE_SHEET_FRAMES_REQUEST = "DRAW_SPRITE_SHEET_FRAMES_REQUEST";
export const MSGID_GET_SPRITE_SHEET_FRAME_WIDTH_REQUEST = "GET_SPRITE_SHEET_FRAME_WIDTH_REQUEST";
export const MSGID_GET_SPRITE_SHEET_FRAME_HEIGHT_REQUEST = "GET_SPRITE_SHEET_FRAME_HEIGHT_REQUEST";