//UI -> Worker messages
export const MSGID_IMAGE_REQUEST_RESULT = "IMAGE_REQUEST_RESULT";
export const MSGID_CONTEXT_REQUEST_RESULT = "CONTEXT_REQUEST_RESULT";
export const MSGID_CANVAS_EVENT = "CANVAS_EVENT";
export const MSGID_DRAW_CANVAS_BUFFER_DONE = "DRAW_CANVAS_BUFFER_DONE";

//Worker -> UI messages
export const MSGID_SHOW_CANVAS = "SHOW_CANVAS";
export const MSGID_HIDE_CANVAS = "HIDE_CANVAS";
export const MSGID_SET_CANVAS_WIDTH = "SET_CANVAS_WIDTH";
export const MSGID_SET_CANVAS_HEIGHT = "SET_CANVAS_HEIGHT";
export const MSGID_CLEAR_CANVAS = "CLEAR_CANVAS";
export const MSGID_CLEAR_RECT = "CLEAR_RECT";
export const MSGID_LOAD_IMAGE_REQUEST = "LOAD_IMAGE_REQUEST";
export const MSGID_UNLOAD_IMAGE_REQUEST = "UNLOAD_IMAGE_REQUEST";
export const MSGID_DRAW_IMAGE_REQUEST = "DRAW_IMAGE_REQUEST";
export const MSGID_DRAW_IMAGE_CLIP_REQUEST = "DRAW_IMAGE_CLIP_REQUEST";
export const MSGID_DRAW_IMAGE_TILED_REQUEST = "DRAW_IMAGE_TILED_REQUEST";
export const MSGID_GET_IMAGE_WIDTH_REQUEST = "GET_IMAGE_WIDTH_REQUEST";
export const MSGID_GET_IMAGE_HEIGHT_REQUEST = "GET_IMAGE_HEIGHT_REQUEST";
export const MSGID_ENABLE_CANVAS_BUFFER = "ENABLE_CANVAS_BUFFER";
export const MSGID_DISABLE_CANVAS_BUFFER = "DISABLE_CANVAS_BUFFER";
export const MSGID_DRAW_CANVAS_BUFFER = "DRAW_CANVAS_BUFFER";
export const MSGID_DRAW_CANVAS_BUFFER_CLIP = "DRAW_CANVAS_BUFFER_CLIP";
export const MSGID_ADD_CANVAS_EVENT = "ADD_CANVAS_EVENT";
export const MSGID_REMOVE_CANVAS_EVENT = "REMOVE_CANVAS_EVENT";
export const MSGID_DRAW_TEXT = "DRAW_TEXT";
export const MSGID_DRAW_RECT = "DRAW_RECT";
export const MSGID_DRAW_CIRCLE = "DRAW_CIRCLE";
export const MSGID_DRAW_LINE = "DRAW_LINE";
export const MSGID_SET_TEXT_FONT = "SET_TEXT_FONT";
export const MSGID_SET_FILL_COLOR = "SET_FILL_COLOR";
export const MSGID_SET_LINE_COLOR = "SET_LINE_COLOR";
export const MSGID_SET_LINE_SIZE = "SET_LINE_SIZE";
export const MSGID_GET_TEXT_DRAW_WIDTH_REQUEST = "GET_TEXT_DRAW_WIDTH_REQUEST";
export const MSGID_GET_TEXT_DRAW_HEIGHT_REQUEST = "GET_TEXT_DRAW_HEIGHT_REQUEST";
